name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        fortran_compiler: [gfortran, ifort]
        os: [ubuntu-latest, macos-latest] # issue with windows-latest & CMake with CMake not recognizing defined compilers

    steps:

    - name: Setup IFORT
      if: contains( matrix.fortran_compiler, 'ifort' )
      uses: modflowpy/install-intelfortran-action@v1

    - name: Setup GFORTRAN
      if: contains( matrix.fortran_compiler, 'gfortran')
      uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 12
        
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}
        CC: ${{ steps.setup-fortran.outputs.cc }}

    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=${{ env.CC }} -DCMAKE_Fortran_COMPILER=${{ env.FC }} -DBUILD_TESTING=TRUE
      
    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test with CMake
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
